In [1]:
import numpy as np 

$$ \dot{V} = Y - [\Gamma^T Y] - \Xi^T I^r - C $$ 

With : 
$$Y = K/\nu$$
$$L = K/a$$
$$I^r = \delta K + \pi K/\nu$$ 
$$\pi = 1 - \Gamma.1 - \delta\nu \Xi.1$$
$$C = C^{pond} \sum(w L)$$

What this program does is, given : $\lambda$,$w$, $\Gamma$,$\Xi$,$C^{pond}$,$\delta$,$\nu$,$p$,$a$ returns the value of $K$ so that we have market-clearing conditions respecting the employment


In [108]:


def dotV_for_p(p):
    Y = K/nu 
    L = K/a
 
    Inter = np.matmul(np.transpose(Gamma),Y) 
    C = Cpond*sum(w*L)/p

    Pi = p*Y - w*L- Y*np.matmul(Gamma,p)/p - delta*K* np.matmul(Xi,p)
    Ir = Pi/(np.matmul(Xi,p)) + K*delta

    return Y - Inter - C - np.matmul(np.transpose(Xi),Ir)

In [ ]:
# Monosectoral
Gamma = np.array([0.1])
Xi = np.array([1. ])
Cpond = np.array([1.]) 
delta = np.array([0.05])
nu =np.array([3. ])
p = np.array([1.])
w=np.array([.6])


In [124]:
# TYPICAL 3-SECTORAL
from scipy.optimize import fsolve

Gamma = np.array([  [0,.1,0],
                    [0,.1,0],
                    [0,.1,0]])
Xi    = np.array([  [0,0,1],
                    [0,0,1],
                    [0,0,1]])
Cpond = np.array([1,0,0])
delta = np.array([0.05,0.05,0.05])
nu    = np.array([3.,3.,3.])
p     = np.array([1.05,1.,1.])
a     = np.array([3,2,1])
w     = np.array([0.4,0.5,.6])  
Kini = np.array([1.,1.,1.])
employment = .9

K = fsolve(dotV_for_K,Kini)
L = np.sum(K/a)
Neq = L/employment
K/=Neq
print(K,dotV_for_K(K))

[1.27364185 0.17907445 0.38631791] [-0.00057488 -0.00160966  0.00019163]


c:\ProgramData\Anaconda3\envs\py3.11\Lib\site-packages\scipy\optimize\_minpack_py.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)


In [129]:
# TYPICAL 3-SECTORAL
from scipy.optimize import fsolve

Gamma = np.array([  [0,.1,0],
                    [0,.1,0],
                    [0,.1,0]]) 
#Gamma = 0.1*np.random.lognormal(size=(3,3))
#print(Gamma)
Xi    = np.array([  [0,0,1],
                    [0,0,1],
                    [0,0,1]])
Cpond = np.array([1,0,0])
delta = np.array([0.05,0.05,0.05])
nu    = np.array([3.,3.,3.])
p     = np.array([1.05,1.,1.])
a     = np.array([3,2,1])
w     = np.array([0.4,0.5,.6])  
Kini = np.array([1.,1.,1.])
employment = .9

K = fsolve(dotV_for_K,Kini)
L = np.sum(K/a)
Neq = L/employment
K/=Neq
print(K,dotV_for_K(K))

[[0.32792069 0.11706981 0.0219704 ]
 [0.06907997 0.03987691 0.36557226]
 [0.01772603 0.03077198 0.19067264]]
[1.77272727 0.29545455 0.18181818] [-0.01009051  0.02351499 -0.02652091]


In [130]:
# TYPICAL 4-SECTORAL intermediate consumption
# sector 1 consumption 
# sector 2 good for sector 1 
# sector 3 good for sector 2 
# sector 4 Capital
from scipy.optimize import fsolve


def dotV_for_K(K,Gamma,Xi,Cpond,delta,nu,p,a,w):
    Y = K/nu 
    L = K/a
 
    Inter = np.matmul(np.transpose(Gamma),Y) 
    C = Cpond*sum(w*L)/p

    Pi = p*Y - w*L- Y*np.matmul(Gamma,p)/p - delta*K* np.matmul(Xi,p)
    Ir = Pi/(np.matmul(Xi,p)) + K*delta

    return Y - Inter - C - np.matmul(np.transpose(Xi),Ir)
    
Gamma = np.array([  [0,.1,0 , 0, 0],
                    [0, 0,.1, 0, 0],
                    [0, 0, 0,.1, 0],
                    [0, 0, 0, 0, 0]]) 
Xi    = np.array([  [0,0,0,1],
                    [0,0,0,1],
                    [0,0,0,1],
                    [0,0,0,1]])
Cpond = np.array([1,0,0,0])
delta = np.array([.05,.05,.05,.05])
nu    = np.array([3.,3.,3.,3.])
p     = np.array([1.,1.,1.,1.])
a     = np.array([3 ,3 ,3 ,3 ])
w     = np.array([.5,.5,.5,.5])  



Kini  = np.array([1.,1.,1.,1.])
employment = .9




K = fsolve(dotV_for_K,Kini,args=[Gamma,Xi,Cpond,delta,nu,p,a,w])
L = np.sum(K/a)
Neq = L/employment
K/=Neq
print(K,dotV_for_K(K))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 5)